class AppConfig {
  /// TODO: Add your Gemini API Key here
  /// You can get one from https://aistudio.google.com/
  static const String geminiApiKey = 'AIzaSyDUSziWQxOnaZhUqs5FBidwnoO0Raz5GGU';

  /// Google Web Client ID - Required for Google Sign-In on Web
  /// You can find this in the Google Cloud Console or Firebase Console
  static const String googleWebClientId = '961435398392-357h40qngsrps5kinl4d93cfpgd8ukgt.apps.googleusercontent.com';

  /// Firebase Options - These are usually generated by `flutterfire configure`
  static const bool isFirebaseConfigured = true;

  /// Default Profile Picture URL
  static const String defaultProfilePic = 'https://instagram.ftun1-2.fna.fbcdn.net/v/t51.2885-19/460897421_7386379758131362_4381940916790910346_n.jpg?stp=dst-jpg_s150x150_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby4xMDgwLmMyIn0&_nc_ht=instagram.ftun1-2.fna.fbcdn.net&_nc_cat=110&_nc_oc=Q6cZ2QFTbpuHask218I_APFh5Iv7zZzMpN5wE0-1FFh-9mZxjoKcRX19UsZKh-mkoESI3Eh29A3BRQn30BRNoZ8k5sIq&_nc_ohc=yk5TZ7jnouUQ7kNvwFleZZj&_nc_gid=RyedfAu7a4BMaeFgfTcEiQ&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_Afrd-SvfGrrBWRYuGLvdIJ6jJkc9RzfxT7YmurSGYWogfw&oe=69660179&_nc_sid=7a9f4b';
}
